//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class information
    {
        public int idPlace { get; set; }
        public int idTime { get; set; }
        public int numPepol { get; set; }
        public int avg { get; set; }
        public int stieeeeeeee { get; set; }
        public int max { get; set; }
        public int min { get; set; }
        public string timeofYaer { get; set; }
        public string commend { get; set; }
        public int idperson { get; set; }
        public int idinfo { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Place Place { get; set; }
        public virtual time time { get; set; }
    }
}
