//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities7 : DbContext
    {
        public DataEntities7()
            : base("name=DataEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<information> information { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Sale_Time> Sale_Time { get; set; }
        public virtual DbSet<time> time { get; set; }
        public virtual DbSet<Updates> Updates { get; set; }
        public virtual DbSet<prop> prop { get; set; }
        public virtual DbSet<store> store { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
    }
}
