//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class prop
    {
        public int Cleanlike { get; set; }
        public int Parkinglike { get; set; }
        public int DParkinglike { get; set; }
        public int Eleveterlike { get; set; }
        public int Negisotlike { get; set; }
        public int id_sale { get; set; }
        public int id_store { get; set; }
        public int Cleandislike { get; set; }
        public int Parkingdislike { get; set; }
        public int DParkingdislike { get; set; }
        public int Elevatordislike { get; set; }
        public int Negisotdislike { get; set; }
        public int id_prop { get; set; }
    
        public virtual Sale_Time Sale_Time { get; set; }
        public virtual store store { get; set; }
    }
}
