//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class prop
    {
        public bool AC { get; set; }
        public bool Parking { get; set; }
        public bool DParking { get; set; }
        public bool Eleveter { get; set; }
        public string Negisot { get; set; }
        public int id_sale { get; set; }
        public int id_store { get; set; }
        public int idPlace { get; set; }
    }
}
